- datafusion/tests/test_context.py
- src/context.rs
Allows passing SessionContext configuration via keyword arguments, as suggested by a TODO comment. I wasn't sure how to deal with `config_options` so I left it out. The unit test also only verifies the `database` and `schema` arguments as I don't think there's currently a way to read the config from Python.
> Add session context config args

- docs/source/python/api.rst
- docs/source/python/api/dataframe.rst
- docs/source/python/api/execution_context.rst
- docs/source/python/api/expression.rst
- docs/source/python/api/functions.rst
- docs/source/python/generated/datafusion.DataFrame.rst
- docs/source/python/generated/datafusion.Expression.rst
- docs/source/python/generated/datafusion.SessionContext.rst
- docs/source/python/generated/datafusion.functions.rst
- docs/source/python/index.rst
Per DataFusion issue about moving the python doc into the python repo: https://github.com/apache/arrow-datafusion/issues/2866
This just moves the docs into the correct project, does not include building/publishing instructions.
> moved python docs from DataFusion project

- .gitignore
- datafusion/tests/test_dataframe.py
- src/dataframe.rs
> [DataFrame] - Add DataFrame::distinct binding

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
Close #27 
`except` is a keyword in Python and cannot be used as a function name, I replaced it with `except_all` like [PySpark `except_All`](https://github.com/apache/spark/blob/d4c58159925133771d305cc7ac4f1248f215812c/python/pyspark/sql/dataframe.py#L487-L513).
> [DataFrame] - Add intersect and except bindings for DataFrame

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
> [DataFrame] - Add collect_partitioned funcation for dataframe

- datafusion/__init__.py
- datafusion/tests/test_config.py
- src/config.rs
- src/expression.rs
- src/lib.rs
> [Config] - Support for key-value pair configuration settings

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_context.py
- src/context.rs
N/A
I want to be able to configure the context.
```python
config_options = {
"datafusion.execution.parquet.enable_page_index": "true",
"datafusion.execution.parquet.pushdown_filters": "true",
"datafusion.execution.parquet.reorder_filters": "true",
}
ctx = datafusion.SessionContext(config_options = config_options)
```
SessionContext::new() has a new argument for config options dict / hash map
> allow config options to be passed to context

- .github/workflows/build.yml
Part of https://github.com/apache/arrow-datafusion-python/issues/7
We want to vote on the release candidate wheels and then publish those wheels to PyPi when the vote passes, rather than building new wheels when we tag the release.
Change the pattern from `"*"` to `"*-rc*"`
> Only build wheels on rc tags

- dev/release/README.md
- dev/release/create-tarball.sh
Part of https://github.com/apache/arrow-datafusion-python/issues/7
Document how to do a release based on recent experience
Docs
> Update release instructions

- .github/workflows/build.yml
As agreed at https://github.com/apache/arrow-datafusion-python/pull/85 the version of manylinux is bumped from 2010 to 2014
Reason: Maturin 0.14.+ does not support manylinux 2010 anymore
Related to #84 .
Maturin 0.14.0 and newer does not support manylinux 2010
Some older versions of Python are not supported anymore.
> Build for manylinux 2014

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/test.yaml
Closes #94 .
Reduce warnings from Github actions.
Update github actions to their latest versions to solve some of the warnings.
Added a dependabot config that will send PRs whenever a new version of an action is available.
No.
> Fix GitHub actions warnings

- .asf.yaml
Issue #39 .
To auto-update the documentation whenever something is pushed to the `asf-site` branch.
Adds `publish` section in `.asf.yaml` so that it publishes to https://arrow.apache.org/datafusion-python
No
> Issue #39 - Add .asf.yaml for asf-site

- .asf.yaml
Related to #39 .
Add entries to .asf.yaml for publishing the docs for asf-site and asf-staging.
See https://github.com/apache/arrow-datafusion-python/pull/104#discussion_r1041493094
Infra stuff
No
> Add entries for publishing production (asf-site) and staging docs

- .github/workflows/test.yaml
- Cargo.lock
- Cargo.toml
- datafusion/tests/test_config.py
- datafusion/tests/test_dataframe.py
- dev/python_lint.sh
- src/catalog.rs
- src/config.rs
- src/context.rs
- src/dataframe.rs
- src/dataset_exec.rs
- src/functions.rs
- src/udaf.rs
Closes https://github.com/apache/arrow-datafusion-python/issues/134
Upgrade to pick up latest features
> Upgrade to DataFusion 16.0.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Part of https://github.com/apache/arrow-datafusion-python/issues/136
- change version
- update changelog
> Prepare for 0.8.0 release

- datafusion/tests/test_functions.py
Closes #128
Improve test coverage for buit-in functions
- Expand tests for math functions
- Expand tests for string functions
- Expand tests for hash functions
- Add tests for temporal functions
No
> test: Expand tests for built-in functions

- src/catalog.rs
- src/context.rs
- src/dataframe.rs
- src/errors.rs
- src/pyarrow_filter_expression.rs
- src/udaf.rs
- src/udf.rs
- src/utils.rs
> Fix clippy for new Rust version

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
- src/lib.rs
- src/logical.rs
- src/physical_plan.rs
> Add DataFrame methods for accessing plans

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
- src/lib.rs
- src/logical.rs
- src/physical_plan.rs
N/A
Making more functionality available in Python
- `DataFrame.logical_plan()`
- `DataFrame.optimized_logical_plan()`
- `DataFrame.execution_plan()`
> Expose methods on logical and execution plans

- datafusion/tests/test_udaf.py
- src/catalog.rs
- src/config.rs
- src/context.rs
- src/dataframe.rs
- src/expression.rs
- src/udaf.rs
- src/udf.rs
Closes #158.
Improve developer experience
Implement `__repr__` methods of the following classes:
- DataFrame
- Expression
- Context
- Catalog
- Database
- Table
- Config
- UDAF & UDF
Display additional information when debugging or using REPL tools
> feature: Improve string representation of datafusion classes

- datafusion/tests/test_substrait.py
- src/context.rs
N/A
I want to be able to execute a substrait plan and there is no way to do that after deserializing a logical plan from substrait.
Change `from_substrait_plan` to return `DataFrame` instead of `LogicalPlan`
> Make from_substrait_plan return DataFrame instead of LogicalPlan

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
Closes #151
Implement count method in Python bindings after it got introduced in Rust.
Make `.count()` available
> feature: Implement count method

- datafusion/tests/test_aggregation.py
- src/functions.rs
Closes #32
Updates #72
Add additional datafusion function to Python bindings
Add aggregate functions and write unit tests:
Add two scalar functions:
Additional aggregate functions
> feature: Add additional aggregation functions

- datafusion/__init__.py
- datafusion/tests/test_context.py
- src/context.rs
- src/lib.rs
Closes https://github.com/apache/arrow-datafusion-python/issues/157
Allow users to configure sessions, including memory and disk settings.
- Expose `SessionConfig` and `RuntimeConfig` in Python so that `SessionContext` is fully configurable.
Yes
> Make session configurable

- datafusion/tests/test_dataframe.py
- datafusion/tests/test_functions.py
Closes #72
Closes #135
Confirm window functions work by adding unit tests.
- Test all window functions
- Fix non-deterministic unit test by sorting results before assertion
- Add unit test for `date_bin` function (fixed by apache/arrow-datafusion#4853)
n/a
> test: Window functions

- datafusion/tests/test_dataframe.py
- src/context.rs
- src/lib.rs
- src/physical_plan.rs
- src/record_batch.rs
N/A
Allow Python code to execute a Rust ExecutionPlan and fetch the stream of batches.
> Add ability to execute ExecutionPlan and get a stream of RecordBatch

- CHANGELOG.md
> [branch-0.8] Update changelog for 0.8 release

- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/filter.rs
Part of https://github.com/apache/arrow-datafusion-python/issues/191
> Add Python wrapper for LogicalPlan::Filter

- dev/release/verify-release-candidate.sh
> Run `maturin develop` instead of `cargo build` in verification script

- README.md
- datafusion/tests/test_dataframe.py
- examples/sql-to-pandas.py
- src/dataframe.rs
Closes #139.
Convert datafusion dataframe directly to a pandas dataframe
Implement `to_pandas()` method using pyarrow library
New `to_pandas()` method
> Implement `to_pandas()`

- Cargo.lock
- datafusion/cudf.py
- examples/sql-on-cudf.py
> Add support for cudf as a physical execution engine

- README.md
- examples/README.md
- examples/dataframe-parquet.py
- examples/sql-on-pandas.py
- examples/sql-on-polars.py
- examples/sql-parquet.py
- examples/substrait.py
N/A
Help users understand if DataFusion Python is a good fit
- Move substrait example into script
- Update README ([rendered version](https://github.com/andygrove/arrow-datafusion-python/tree/readme-0.8#readme))
> Update README in preparation for 0.8 release

- datafusion/__init__.py
- datafusion/pandas.py
- datafusion/polars.py
- datafusion/tests/test_context.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/analyze.rs
- src/sql/logical.rs
> Analyze table bindings

- README.md
- examples/README.md
- examples/sql-on-cudf.py
> Minor docs updates

- src/expr.rs
> wrap display_name and canonical_name functions

- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/alias.rs
> Add PyAlias bindings

- datafusion/__init__.py
- datafusion/cudf.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/scalar_variable.rs
> Add bindings for scalar_variable

- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/like.rs
> Bindings for LIKE type expressions

- Cargo.lock
- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/case.rs
- src/expr/cast.rs
> Add bindings for case, cast, and trycast

- Cargo.lock
- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/exists.rs
- src/expr/grouping_set.rs
- src/expr/in_list.rs
- src/expr/in_subquery.rs
- src/expr/placeholder.rs
- src/expr/scalar_function.rs
- src/expr/scalar_subquery.rs
- src/expr/signature.rs
- src/expr/subquery.rs
> add remaining expr bindings

- .github/workflows/build.yml
- dev/release/README.md
N/A
Development of the Python bindings has been lagging behind DataFusion because we have to wait four weeks to get the next DataFusion release before we can update the Python bindings.
I would like to change our release process and branch policy so that we can keep the main branch branch up-to-date with the latest DataFusion using GitHub dependencies and then create release branches when we are ready to create a new release.
- Documentation for new release process ([rendered version](https://github.com/andygrove/arrow-datafusion-python/blob/release-process/dev/release/README.md))
- Modification to one workflow
No
> Implement new release process

- datafusion/tests/test_dataframe.py
- examples/export.py
- src/dataframe.rs
Closes #234
Closes #235 
Implement additional export functions and fix bug if datafusion dataframe is empty
- Implement `to_arrow_table()`, `to_pylist()` and `to_pydict()`
- Return empty dataframe/list/table instead of error if datafusion dataframe is empty
- Document these export functions
See above
> feature: Additional export methods

- datafusion/tests/test_context.py
- examples/export.py
- examples/import.py
- src/context.rs
Closes #241.
Better integration with Python language & popular libraries
- Implement functions that construct datafusion DataFrames:
- Document new functions
New context functions listed above
> feature: Create dataframe from pandas, polars, dictionary, list or pyarrow Table

- README.md
- datafusion/__init__.py
- examples/sql-using-python-udaf.py
- examples/sql-using-python-udf.py
Closes #138
Document how to utilize Python UDFs & UDAFs in SQL
Document examples & link in README.md
Additional examples/documentation
> docs: Example of calling Python UDF & UDAF in SQL

- datafusion/tests/test_context.py
- examples/sql-using-python-udaf.py
- examples/sql-using-python-udf.py
- src/context.rs
Closes #259 
Possibility to set table name when constructing dataframe from Arrow table/Python dictionary/pandas/polars
See above
Optional `name` parameter in `create_dataframe` and `from_` functions
> feature: Set table name from ctx functions

- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/repartition.rs
> Bindings for LogicalPlan::Repartition

- src/errors.rs
- src/expr/literal.rs
> Expand Rust return type support for Arrow DataTypes in ScalarValue

- src/expr/literal.rs
Closes #.
Got a warning when verifying 20.0.0 RC 2 release:
```
warning: unused import: `py_runtime_err` 386/387: datafusion-python                                                                                                                                                                  
--> src/expr/literal.rs:18:21
|
18 | use crate::errors::{py_runtime_err, DataFusionError};
|                     ^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: 1 warning emitted===========> ] 386/387: datafusion-python                                                                                                                                                                  
```
> minor: Fix minor warning on unused import

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
Closes #292 
Expose newly added `describe()` in Python language bindings
New method `describe()` and Python unit test
New method available
> feature: Implement `describe()` method

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_dataframe.py
- datafusion/tests/test_indexing.py
- datafusion/tests/test_store.py
- src/common/df_field.rs
- src/context.rs
- src/dataframe.rs
- src/expr/column.rs
- src/expr/table_scan.rs
> Upgrade to DF 21

- .github/workflows/build.yml
> Fix release build

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
> Enable datafusion-substrait protoc feature, to remove compile-time dependency on protoc

- .github/workflows/docs.yaml
- docs/README.md
- docs/build.sh
- docs/requirements.txt
- docs/source/api.rst
N/A
Docs workflow is failing
Specify specific sphinx version to fix errors regarding 'logo'. Fix an error in the index.
> Fix documentation generation in CI

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- datafusion/tests/test_context.py
- datafusion/tests/test_dataframe.py
- datafusion/tests/test_indexing.py
N/A
- Bump version to 22.0.0
- Depend on DataFusion 22.0.0
- [CHANGELOG](https://github.com/andygrove/arrow-datafusion-python/blob/prep-22/CHANGELOG.md)
> Prepare for 22.0.0 release

- .github/workflows/build.yml
Closes https://github.com/apache/arrow-datafusion-python/issues/337
> mac arm64 build

- src/context.rs
- src/lib.rs
- src/utils.rs
Closes #340 
Currently, we create a new Tokio Runtime and associated threads often which is not good for performance. This PR uses a module level attribute to create this once and reuse it.
No.
> Reuse the Tokio Runtime

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_substrait.py
- examples/substrait.py
- src/errors.rs
- src/substrait.rs
Also, Clean up existing Substrait bindings to return bytes instead of List[int].
Closes #343 
What we had before didn't allow for serializing a Substrait plan to ProtoBuf. You had to use a SQL query which was awkward. This also fixes the `substrait` module return types to be `bytes` instead of `List[int]` which is also awkward.
Add `encode` method to `datafusion.substrait.plan`. Also change datafusion.substrait return types to be `bytes` instead of `List[int]`.
Yes, but IMO changes for the better.
> Add interface to serialize Substrait plans to Python Bytes.

- datafusion/tests/test_dataframe.py
- examples/substrait.py
- src/physical_plan.rs
Closes #345 
This helps create Arrow Flight tickets for a particular partition number.
Add `partition_count` property to `ExecutionPlan`.
Only additions.
> Add partition_count property to ExecutionPlan.

- src/context.rs
- src/store.rs
- src/substrait.rs
Closes #347 
Python objects are free to move about the Python interpreter threads and users expect to be able to use objects from different threads.
Removes all `#[pyclass(unsendable)]` markers from our code and prevents unexpected panics from Python users.
No.
> Remove unsendable from all Rust pyclass types.

- src/context.rs
Closes #351 
The execute function in SessionContext didn't work before.
Fix the SessionContext execute function to use the existing SessionState.
No.
> Fix SessionContext execute.

- benchmarks/tpch/.gitignore
- benchmarks/tpch/README.md
- benchmarks/tpch/create_tables.sql
- benchmarks/tpch/queries/q1.sql
- benchmarks/tpch/queries/q10.sql
- benchmarks/tpch/queries/q11.sql
- benchmarks/tpch/queries/q12.sql
- benchmarks/tpch/queries/q13.sql
- benchmarks/tpch/queries/q14.sql
- benchmarks/tpch/queries/q15.sql
- benchmarks/tpch/queries/q16.sql
- benchmarks/tpch/queries/q17.sql
- benchmarks/tpch/queries/q18.sql
- benchmarks/tpch/queries/q19.sql
- benchmarks/tpch/queries/q2.sql
- benchmarks/tpch/queries/q20.sql
- benchmarks/tpch/queries/q21.sql
- benchmarks/tpch/queries/q22.sql
- benchmarks/tpch/queries/q3.sql
- benchmarks/tpch/queries/q4.sql
- benchmarks/tpch/queries/q5.sql
- benchmarks/tpch/queries/q6.sql
- benchmarks/tpch/queries/q7.sql
- benchmarks/tpch/queries/q8.sql
- benchmarks/tpch/queries/q9.sql
- benchmarks/tpch/tpch-gen.sh
- benchmarks/tpch/tpch.py
- dev/release/rat_exclude_files.txt
- src/context.rs
N/A
Make it easier to run benchmarks so we can track performance between releases and catch regressions earlier.
I had to add a workaround for https://github.com/apache/arrow-datafusion/issues/6147 by renaming the generated `.tbl` files to `.csv` files.
> Add benchmark derived from TPC-H

- src/common/data_type.rs
> Add  'pub' and '#[pyo3(get, set)]' to DataTypeMap

- .dockerignore
- benchmarks/db-benchmark/README.md
- benchmarks/db-benchmark/db-benchmark.dockerfile
- benchmarks/db-benchmark/groupby-datafusion.py
- benchmarks/db-benchmark/join-datafusion.py
- benchmarks/db-benchmark/run-bench.sh
Closes #368 
```
$ docker run --privileged -it db-benchmark
loading dataset data/G1_1e7_1e2_0_0.csv
dataset loaded
registered record batches
q1: 0.3676629539113492
q2: 2.19574227090925
q3: 5.529615408042446
q4: 0.4646788500249386
q5: 5.782891046954319
q6: 8.021909267874435
q7: 4.6340672872029245
q8: 2.5885365640278906
q9: 7.149171598022804
q10: 7.976435187039897
grouping finished, took 45s
```
We want to be able to run the benchmarks in this repo easily.
TBD
> Fix db-benchmark

- .gitignore
- src/expr.rs
> Add Expr::Case when_then_else support to rex_call_operands function

- .gitignore
- datafusion/context.py
- datafusion/cudf.py
- datafusion/pandas.py
- datafusion/polars.py
- docs/mdbook/src/usage/create-table.md
- examples/sql-on-pandas.py
- examples/sql-on-polars.py
> Introduce BaseSessionContext abstract class

- datafusion/tests/test_dataframe.py
- datafusion/tests/test_expr.py
- src/dataframe.rs
Expose the `offset` parameter of `limit` in the Python API
> feat: expose offset in python API

- .github/workflows/build.yml
Closes #426.
As a user on a Linux aarch64 (ARM64) system, I have faced challenges when trying to install DataFusion from pip. Currently, the pre-built wheel is only available for x86_64 architecture on Linux, leaving ARM-based systems unsupported. To address this issue and enhance the usability of DataFusion in ARM environments, I propose the inclusion of a pre-built DataFusion wheel specifically for Linux aarch64.
This PR includes the addition of a pre-built DataFusion wheel for Linux aarch64 (ARM64) architecture, making it easier for users to install DataFusion on ARM-based systems without the need to build it from source.
No, there are no user-facing changes in this PR. The introduction of the pre-built wheel is meant to simplify the installation process for Linux aarch64 users without …
> Build Linux aarch64 wheel

- datafusion/tests/test_functions.py
- src/expr.rs
- src/expr/conditional_expr.rs
- src/functions.rs
Closes #447 
Besides exposing the case function, this PR also adds the PyCaseBuilder class (to parallel Rust's CaseBuilder)
Yes, but the documentation should be generated automatically
> feat: add case function (#447)

- docs/requirements.txt
- docs/source/conf.py
- docs/source/contributor-guide/introduction.rst
- docs/source/index.rst
- docs/source/user-guide/basics.rst
- docs/source/user-guide/common-operations/aggregations.rst
- docs/source/user-guide/common-operations/basic-info.rst
- docs/source/user-guide/common-operations/functions.rst
- docs/source/user-guide/common-operations/index.rst
- docs/source/user-guide/common-operations/joins.rst
- docs/source/user-guide/common-operations/select-and-filter.rst
- docs/source/user-guide/common-operations/udf-and-udfa.rst
- docs/source/user-guide/common-operations/windows.rst
- docs/source/user-guide/introduction.rst
- docs/source/user-guide/io/avro.rst
- docs/source/user-guide/io/csv.rst
- docs/source/user-guide/io/index.rst
- docs/source/user-guide/io/json.rst
- docs/source/user-guide/io/parquet.rst
- docs/source/user-guide/sql.rst
Closes #432 
This PR includes additional changes in the documentation to make it coherent with the User Guide and the documentation from the DataFusion main project
Yes, the documentation page will change.
> enhancement(docs): Add user guide (#432)

- README.md
- docs/source/contributor-guide/introduction.rst
Closes #454 
This PR also includes fixes for some typos and links to the section
No
> docs: include pre-commit hooks section in contributor guide

- datafusion/tests/test_context.py
- datafusion/tests/test_sql.py
- src/context.rs
Closes #133.
Yes, the `register_csv`, `read_csv`, `read_json` functions now have the optional argument `file_compression_type=None`
> feat: add compression options

- datafusion/tests/test_sql.py
- src/context.rs
This PR closes the `register_json` request in #24. 
Adds the `register_json` function to the `SessionContext`
Yes
> feat: add register_json

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
Closes #116.
Only compression for all columns was added, later we could a per column compression argument
Yes, two new parameters were added but this should be reflected automatically by Sphinx,
> feat: add basic compression configuration to write_parquet

- datafusion/tests/test_context.py
- datafusion/tests/test_sql.py
- src/context.rs
Partially addresses #24
The method `register_avro` was added
Yes
> feat: add register_avro and read_table

- datafusion/tests/test_functions.py
- src/functions.rs
Partially addresses #463.
It will be nice for UX to have the full set of functions provided by `rust-datafusion`
The following scalar math functions were added:
- acosh
- asinh
- atanh
- cbrt
- cosh
- degrees
- factorial
- gcd
- lcm
- nanvl
- pi
- radians
- sinh
- tanh
Yes
> feat: add missing scalar math functions

- .github/workflows/build.yml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
This reverts commit 944b1c98343aeae3dd6d2d82525a27068d5fb12d.
Closes #472.
This follows the suggestion from https://github.com/arduino/setup-protoc/issues/85. Based on it, setup-protoc@v2 is for [v21.0](https://github.com/protocolbuffers/protobuf/tree/v21.0). We should setup-protoc@v1.
> Revert "build(deps): bump arduino/setup-protoc from 1 to 2 (#452)"

- Cargo.lock
- Cargo.toml
- src/context.rs
- src/dataframe.rs
> Upgrade to Datafusion 31.0.0

- CHANGELOG.md
- Cargo.lock
N/A
Scheduled release
- Ran `cargo update`
- Updated [changelog](https://github.com/andygrove/arrow-datafusion-python/blob/prep-31/CHANGELOG.md)
> Prepare 31.0.0 release

- datafusion/tests/test_functions.py
- src/functions.rs
part of https://github.com/apache/arrow-datafusion-python/issues/463
> add Binary String Functions;encode,decode 

- datafusion/tests/test_functions.py
- src/functions.rs
> add first_value last_value

- datafusion/tests/test_functions.py
- src/functions.rs
> add regr_* functions

- datafusion/__init__.py
- datafusion/tests/test_dataframe.py
- src/functions.rs
- src/lib.rs
- src/udaf.rs
- src/window_frame.rs
Partial progress on #191 : Expressions: Window function
This PR
- adds `PyWindowFrame`
- modifies `functions.window` to accept an optional `PyWindowFrame` and optional `PySessionContext`
- `PySessionContext` is necessary to look up aggregates registered via `PySessionContext.register_udaf`
- modifies `function.window` to fall back to `SessionContext.udaf` when `find_df_window_func` fails
- modifies `Accumulator` impl for `RustAccumulator` to expose `retract_batch` and `supports_retract_batch`
`PyWindowFrame` needs to be documented as do changes to `functions.window` 
note: I have working code that enables window functions for `ibis` that I still need to create a PR for
> feat: expose PyWindowFrame

- src/expr/aggregate.rs
- src/expr/join.rs
- src/expr/sort.rs
No issue related to this PR. Rather it is a couple of small papercuts that need patched up from missing functions from the first time I wrote the bindings.
> Add random missing bindings

- datafusion/input/location.py
- datafusion/tests/test_input.py
- src/common/schema.rs
> Allow for multiple input files per table instead of a single file

- Cargo.toml
- conda/recipes/meta.yaml
- pyproject.toml
- src/lib.rs
> Remove libprotobuf dep

- Cargo.lock
- Cargo.toml
- src/common/data_type.rs
- src/dataset_exec.rs
- src/expr.rs
- src/expr/window.rs
- src/substrait.rs
- src/udaf.rs
- src/udf.rs
N/A
- Use latest DF
- Fix issues related to pyo3 upgrade
> Upgrade to DataFusion 33.0.0-rc1

- Cargo.toml
We have been experiencing issues in dask-sql with dynamic TLS allocation when building on linux and targeting aarch64. More details on the errors and approaches can be found at https://github.com/dask-contrib/dask-sql/issues/1169
However, it seems practical to me to at least propose enabling the mimalloc `local_dynamic_tls` feature by default in ADP so that downstream libraries do you encounter this sort of behavior. I am open to other suggestions or configuration options as well but just wanted to get something started.
> Enable mimalloc local_dynamic_tls feature

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/common/data_type.rs
- src/common/schema.rs
- src/context.rs
- src/dataframe.rs
- src/dataset_exec.rs
- src/expr.rs
- src/expr/aggregate.rs
- src/expr/aggregate_expr.rs
- src/expr/distinct.rs
- src/functions.rs
- src/udaf.rs
- src/udf.rs
N/A
Prepare for next release
- Upgrade to DataFusion 34
- Update changelog
> Prepare 34.0.0 Release

- datafusion/__init__.py
- src/udaf.rs
This PR does not close an issue but propagates the work of https://github.com/apache/arrow-datafusion/pull/7096 to `arrow-datafusion-python`
The functionality already exists in the underlying rust but is not exposed to the python interface.
`udaf` still accepts a single `pa.lib.DataType` as an input, but also accepts an iterable of `pa.lib.DataType`
All previously working code will still work the same.
> feat: udaf: enable multiple column input

- datafusion/tests/test_functions.py
- src/functions.rs
Part of  #463 
Array functions should be implemented for the Python API.
Array functions:
- array_append
- array_concat
- array_cat
- array_dims
- list_dims
- array_element
- array_extract
- list_element
- list_extract
- array_length
- list_length
Yes.
> Add missing array functions

- src/context.rs
- src/lib.rs
- src/utils.rs
Closes https://github.com/apache/arrow-datafusion-python/issues/581
I would like other projects (such as PyBallista) to be able to re-use the `PyDataFrame` struct.
See https://github.com/apache/arrow-ballista/pull/976 for an example of how this is leveraged.
Make some things public.
> Allow PyDataFrame to be used from other projects

- datafusion/tests/test_functions.py
- src/functions.rs
Part of #463
Add missing array functions for the Python API.
Array functions:
- array_has
- array_has_all
- array_has_any
- array_indexof
- array_join
- array_ndims
- array_pop_back
- array_pop_front
- array_position
- array_positions
- array_prepend
- array_push_back
- array_push_front
- array_remove
- array_remove_all
- array_remove_n
- array_repeat
- array_replace
- array_replace_all
- array_replace_n
- array_slice
- array_to_string
- list_append
- list_indexof
- list_join
- list_ndims
- list_position
- list_positions
- list_prepend
- list_push_back
- list_push_front
- list_remove
- list_remove_all
- list_remove_n
- list_replace
- list_replace_all
- list_replace_n
- list_slice
- list_to_string
Yes.
> Add array functions

- datafusion/tests/test_functions.py
- src/functions.rs
> feat: Add `flatten` array function

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/common/data_type.rs
- src/expr.rs
- src/functions.rs
- src/udaf.rs
> Prepare 36.0.0 Release

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
- src/record_batch.rs
Closes #12 .
Yes, the methods: `execute_stream` and `execute_stream_partitioned` were added to the DataFrame API.
> feat: add execute_stream and execute_stream_partitioned

- datafusion/__init__.py
- datafusion/tests/test_context.py
- src/context.rs
- src/lib.rs
Closes #567.
- Implemented binding
- Added tests
Yes, the user can now instantiate a SQLOptions class and use inside the newly bound method `sql_with_options`.
This is my first open source contribution, so I apologise in advance if there is any mistake in the contribution style!
> Bind SQLOptions and relative ctx method #567

- datafusion/tests/test_context.py
- src/context.rs
> bugfix: no panic on empty table

- datafusion/tests/test_sql.py
- docs/source/index.rst
- docs/source/user-guide/configuration.rst
- src/context.rs
- src/dataframe.rs
Makes it possible to work with partitioned s3 datasets using `object_store` through datafusion.
Also includes some documentation improvements.
Closes #617.
> Expose `register_listing_table`

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
- src/expr.rs
- src/expr/unnest.rs
- src/sql/logical.rs
Closes #640.
This change is fairly straight forward. The unnest feature already exists in the `arrow-datafusion` repository so it just needs the API exposed.
Adding `unnest_column` to dataframe 
Pure addition. No prior code has been modified.
> Expose unnest feature

- .github/workflows/build.yml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
Closes https://github.com/apache/datafusion-python/issues/644 (hopefully)
> use python 3.11 to publish docs

- .github/workflows/docs.yaml
Closes #644 (hopefully)
PR #645 switched to using python 3.11 to publish docs. This updates the dependency installation to use the appropriate requirements file.
none
none
> docs: update docs CI to install python-311 requirements

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_functions.py
- src/catalog.rs
- src/common/data_type.rs
- src/context.rs
- src/dataframe.rs
- src/dataset_exec.rs
- src/expr.rs
- src/functions.rs
- src/physical_plan.rs
- src/udf.rs
- src/utils.rs
NOTE: While each commit is a self-contained "logical" change, the project needs all the commits to compile.
Closes #663. (hopefully)
This is a cleaned up version of #662. 
Importantly, the final failing test is *not* commented out, so there is 1 failing test. 
The error and test case are highlighted in this commit from previous PR: https://github.com/apache/datafusion-python/pull/662/commits/ecff35793e918a3dbdaf9220670d1ca5892b48d3
- Upgrades the dependencies
- All minimal ports for the code to compile and all tests (modulo one failure) to pass
- It does not answer the API questions highlighted in the #663. All choices were w/ the goal of "getting to passing tests".
Much of  `src/functions.rs` have been updated per the upstream epic: https://github.com/apache/datafusion/issues/9285
> Upgrade Datafusion to v37.1.0

- docs/source/user-guide/common-operations/expressions.rst
- docs/source/user-guide/common-operations/index.rst
Closes #667.
The bug report was not an actual bug, but rather a lack of documentation about how to perform the boolean operations on expressions. This change adds in a new page to the documentation that describes a few basics of working with expressions for new users.
This change adds a page under Basic Operations called Expressions and details some basics of creating expressions and performing boolean operations.
Only documentation is changed.
> Add document about basics of working with expressions

- .github/workflows/conda.yml
Closes #659 .
My prior attempt failed at this failed (#664), but I *believe* that was because [conda didn't like](https://github.com/apache/datafusion-python/issues/659#issuecomment-2100566566) the tag `publish-docs` on main.
I was able to reproduce the CI error locally, and running `conda clean` solved it.
Extra build step to CI.
No.
> fix conda nightly builds, attempt 2

- Cargo.lock
The only rust dep that wasn't updated is `mimalloc`. Updating that is causing compilation failures.
---
Closes #672 rustls
Closes #682 syn
Closes #653 parking_lot
Closes #648 object_store
Closes #625 h2
Closes #623 tokio
Closes #608 mio
Closes #597 pyo3
Closes #642 pyo3-build-config
Closes #627 prost
Closes #634 prost-types
Closes #637 async-trait
> chore: update cargo deps

- python/datafusion/tests/test_functions.py
- src/functions.rs
ends_with function is missing from datafusion_python
> feat: add python bindings for ends_with function

- python/datafusion/tests/test_functions.py
- src/functions.rs
Ref #692
Closes #692 
This UDF has not been ported over and was requested.
The UDF is wrapped and exposed to python.
No. Just a function added.
> feat: expose `named_struct` in python

- .github/workflows/test.yaml
- benchmarks/tpch/tpch-gen.sh
- examples/tpch/_tests.py
- examples/tpch/convert_data_to_parquet.py
- examples/tpch/q01_pricing_summary_report.py
- examples/tpch/q02_minimum_cost_supplier.py
- examples/tpch/q03_shipping_priority.py
- examples/tpch/q04_order_priority_checking.py
- examples/tpch/q05_local_supplier_volume.py
- examples/tpch/q06_forecasting_revenue_change.py
- examples/tpch/q07_volume_shipping.py
- examples/tpch/q08_market_share.py
- examples/tpch/q09_product_type_profit_measure.py
- examples/tpch/q10_returned_item_reporting.py
- examples/tpch/q11_important_stock_identification.py
- examples/tpch/q12_ship_mode_order_priority.py
- examples/tpch/q13_customer_distribution.py
- examples/tpch/q14_promotion_effect.py
- examples/tpch/q15_top_supplier.py
- examples/tpch/q16_part_supplier_relationship.py
- examples/tpch/q17_small_quantity_order.py
- examples/tpch/q18_large_volume_customer.py
- examples/tpch/q19_discounted_revenue.py
- examples/tpch/q20_potential_part_promotion.py
- examples/tpch/q21_suppliers_kept_orders_waiting.py
- examples/tpch/q22_global_sales_opportunity.py
- examples/tpch/util.py
- src/functions.rs
Closes #696
Closes #712
This PR sets up a work flow to generate TPH-C 1Gb data set in CI, runs the 22 examples, and compares their results to the
known answer file. By adding this PR we improve the robustness of our test suite.
This PR adds the following changes:
- Adds CI workflow to generate TPH-C data set and answer file. The results are cached from run to run.
- Adds pytest file to run all 22 examples and compare them to the answer file
- Exposes substring operation that was missing. Sometime between 36.0.0 and 38.0.0 substr was performing the operation instead.
`substring` function exposed in python.
This PR replaces https://github.com/apache/datafusion-python/pull/710 which contains a lot of intermediate testing steps. This MR should be cleaner to review.
> tsaucer/run TPC-H examples in CI

- python/datafusion/tests/test_functions.py
Ref #671
All of the tests in `test_functions.py` are overloaded - representing many more than one test case.
This cleans up `test_array_functions`, which becomes 62 different test cases.
test_array_functions now has 56 passing test cases and 1 expected failure (`array_slice` being the expected failure Ref #670).
test_array_function_flatten was broken out as a single test because it was an outlier in terms of test-input.
test_array_function_obj_tests had a different set of asserts, so was broken out for 4 test cases.
No
> test: parametrize test_array_functions

- examples/tpch/convert_data_to_parquet.py
None.
As requested by @andygrove this PR is a small update to the TPC-H data conversion from CSV to parquet. Users at large scales may have a problem of running out of unique keys.
It sets the keys to use int64 instead of int32 and sets all fields as not null.
None.
> Use int64 for TPC-H keys and set input schema to not nullable

- .github/workflows/build.yml
Closes #646.
These build steps were setting `--features protoc`, which I think was over-riding the `features = ["substrait"]` in `pyproject.toml`
There should not be.
> ci: add substrait feature to linux builds

- .github/workflows/docs.yaml
I *think* the condition for deploying the docs was wrong. When a tag is pushed to `main`, the `github.ref` is the tag, not the branch name.
I also added a debug print step because I'm uncertain and would like to verify.
> Docs deploy action

- Cargo.lock
- Cargo.toml
- src/expr.rs
Closes #729
`datafusion` already implements converting `ScalarValue`s to python objects.
ScalarValue types that we hadn't converted like Float16, BigDecimal128 will now be supported.
It should be strictly additive, I think.
> use ScalarValue::to_pyarrow to convert to python object

- Cargo.toml
- src/common.rs
- src/config.rs
- src/context.rs
- src/dataframe.rs
- src/dataset.rs
- src/dataset_exec.rs
- src/expr.rs
- src/functions.rs
- src/lib.rs
- src/pyarrow_filter_expression.rs
- src/store.rs
- src/substrait.rs
- src/udaf.rs
- src/utils.rs
Part of #727 
`pyo3` has deprecated their gil-refs api.
See the [blog announcement](https://polar.sh/davidhewitt/posts/replacing-pyo3-api-pt1) and the [migration guide](https://pyo3.rs/v0.21.0/migration#from-020-to-021).
Migrates to pyo3's `Bound` api
There should not be.
> Pyo3 `Bound<'py, T>` api

- python/datafusion/tests/test_context.py
- src/pyarrow_filter_expression.rs
Closes #703.
The conversion for `IsNull` had a bug.
`datafusion-python` users requested `pyarrow` predicate pushdown support for temporal types.
**`IsNull` bug**
The conversion was incorrectly passing the `column-expression` as an argument to the `pyarrow` method `is_null`. This would **silently** fail and the predicate would be excluded from the plan.
The argument *should* be a scalar for `nan_is_null`. I do not currently have a way for users to pass that in, so please suggest how I might do so.
**Temporal Scalars**
Similar to #731, I used `ScalarValue::to_pyarrow` for the scalar conversion. `pyarrow` filters can now accept anything that already has an upstream conversion.
A bugfix and expanded functionality.
I tested the predicate pushdown in two separate ways.
1) Ensuring that …
> Pyarrow filter pushdowns

- src/context.rs
- src/dataframe.rs
- src/sql/logical.rs
Part of #727.
[pyo3 recommend](https://github.com/PyO3/pyo3/pull/4274) using the Python token from a `Bound<'_, T>` type or automatically passed in as a method parameter for a `#[pymethods]` or `#[pyfunction]` because they are zero-cost.
`Python::with_gil` carries a runtime check overhead.
I changed all the places that had straightforward removal of `Python::with_gil`. 
Additionally, I removed some manual type conversion work by letting pyo3 do it automatically as we cross the python-rust boundary.
No
> Pyo3 refactorings

- Cargo.lock
- Cargo.toml
- examples/tpch/_tests.py
- src/common.rs
- src/common/data_type.rs
- src/functions.rs
Part of #727 
Ref #730
* Provides releasable workaround for but does not close #730.
* Provides python compatibility for `sqlparser::ast::NullTreatment` which is now part of the UDAF api.
`AggregateFunction::Sum` enum variant is still defined upstream, [but can not be used](https://github.com/apache/datafusion/blob/6a4a280e3cf70fe5f1a1cfe7c2de13e4c39f89bb/datafusion/physical-expr/src/aggregate/build_in.rs#L107C1-L109).
I suspect that the proper solution is to register the [new UDAFs with the function registry](https://github.com/apache/datafusion/blob/6a4a280e3cf70fe5f1a1cfe7c2de13e4c39f89bb/datafusion/functions-aggregate/src/lib.rs#L95-L107). 
But I'm unsure how that machinery should work. 
As a workaround for releasing 39, I explicitly match on name == "sum" and redirect to the UDAF. …
> UDAF `sum` workaround 

- python/datafusion/functions.py
- python/datafusion/tests/test_functions.py
- src/functions.rs
No issue logged, but I can add one if someone wants.
The function `array_sort` is not exposed on the python side but exists in the rust repo.
Exposes the function - very straight forward.
Added unit test for both ascending and descending sorts.
> Expose array sort

- Cargo.lock
- Cargo.toml
- docs/requirements.txt
- examples/substrait.py
- python/datafusion/functions.py
- python/datafusion/tests/test_aggregation.py
- python/datafusion/tests/test_dataframe.py
- python/datafusion/tests/test_functions.py
- python/datafusion/tests/test_sql.py
- src/common/data_type.rs
- src/dataset_exec.rs
- src/functions.rs
Part of #776.
Closes #778.
Closes #774.
[Release notes for upstream `datafusion` v40](https://github.com/apache/datafusion/blob/fab7e238e8559bdb2e4e0449354f7efeccbc07a7/dev/changelog/40.0.0.md)
Upstream `datafusion` continues its migration from built-in aggregate functions to User Defined Aggregate Functions. The APIs around these functions have been in serious flux, so the focus of this PR is to upgrade the deps and get all existing tests to pass.
Our `regr_*` func wrappers are now properly tested.
And aliases from `functions.rs` have been removed, leaning on our python wrappers.
> Upgrade Datafusion 40

- examples/python-udf-comparisons.py
None
The current example for python UDF is useful but doesn't demonstrate to a new user how they might implement a UDF using converting rows to python objects vs using features built in to pyarrow. This example shows a real use case where someone could perform such operations. Also it prints out timing results showing how using a pyarrow approach can give you a 10x speed improvement over converting to python objects.
Added one example
None
> Add in user example that compares a two different approaches to UDFs

- python/datafusion/tests/test_expr.py
- src/expr.rs
- src/expr/alias.rs
- src/expr/exists.rs
- src/expr/in_list.rs
- src/expr/in_subquery.rs
- src/expr/placeholder.rs
- src/expr/sort_expr.rs
- src/expr/unnest_expr.rs
- src/sql/logical.rs
Closes #781.
The user bug report filed
> When a SQL query contains a InList Expr, I can't get the InList object through Expr.to_variant().
In fixing this bug, I found that upstream datafusion has added explicit structs for many of the variants, so I also updated the datafusion-python variants for those.
Lastly, `datafusion-python` was incorrectly returning the `logical_plan::Sort` instead of the `expr::Sort` as the variant for the `Expr::Sort`.
- `PyAlias` now wraps `datafusion_expr::expr::Alias`
- `PyExists` now wraps `datafusion_expr::expr::Exists`
- `PyInList` now wraps `datafusion_expr::expr::PyInList`
- `PyInSubquery` now wraps `datafusion_expr::expr::InSubquery` 
- `PyPlaceholder` now wraps `datafusion_expr::expr::Placeholder`
`PyExpr::to_variant` was incorrectly returning variants …
> Add PyExpr to_variant conversions

- Cargo.lock
- Cargo.toml
- python/datafusion/functions.py
- python/datafusion/tests/test_aggregation.py
- src/functions.rs
Closes #777.
Supersedes #794 #785 #739 #732.
When `approx_percentile_cont` was migrated to a UDAf upstream, the `num_centroids` argument was removed from its fluent API.
This works around that by invoking the `AggregateFunction::call` directly.
Though `approx_percentile_cont` is re-enabled, this actually matches the behavior of the last release.
No.
> Re-Enable `num_centroids` to  `approx_percentile_cont` 

- docs/source/user-guide/common-operations/udf-and-udfa.rst
- python/datafusion/tests/test_udaf.py
- python/datafusion/udf.py
- src/udaf.rs
Closes #797 
Currently only the first state variable in a user defined aggregate function is passed to the `merge` stage.
Passes all state variables to the `merge` call.
Yes, any user of udaf will need to change their merge stage to use `states[0]` instead of `states`.
> UDAF process all state variables

- CHANGELOG.md
- dev/release/README.md
- dev/release/generate-changelog.py
- requirements.in
N/A
- Update changelog generator script to match the new version in DataFusion
- Generate the changelog
> chore: Prepare for 40.0.0 release

- pyproject.toml
This is related to https://github.com/apache/datafusion-python/issues/804
#750 introduced wrapper classes that include the `@deprecated` annotation on a few functions. If `typing-extensions` is not installed, `import datafusion` will fail.
Adds typing extensions to the pyproject so that pip will ensure it is installed.
None
> Add typing-extensions dependency to pyproject

- python/datafusion/context.py
- python/datafusion/tests/test_context.py
- src/context.rs
N/A
Enable users to supply a list of csv file paths to the `read_csv` function, inspired by this issue: https://github.com/ibis-project/ibis/issues/9866.
Changes to the `read_csv` function in Rust and the corresponding signature types in Python 
Yes
> feat: enable list of paths for read_csv

- Cargo.lock
- Cargo.toml
- python/datafusion/tests/test_functions.py
- src/catalog.rs
- src/common/data_type.rs
- src/context.rs
- src/dataset.rs
- src/expr/aggregate.rs
- src/expr/aggregate_expr.rs
- src/functions.rs
> [!NOTE]
> This is just the "upgrade the datafusion deps" PR.
> After the deps are upgraded, we can implemented features / bugfixes cleanly on top as we prepare for releasing `datafusion-python` 41
[Datafusion 41.0.0 Changelog](https://github.com/apache/datafusion/blob/27304239ef79b50a443320791755bf74eed4a85d/dev/changelog/41.0.0.md)
Part of #828.
`datafusion` dependencies are upgraded and code updated so the tests pass.
No new upstream features were integrated.
> Upgrade deps to datafusion 41

- python/datafusion/context.py
- python/datafusion/tests/test_context.py
Previously creating a `SessionContext` when specifying only a `SessionConfig` would error.
Fixes #826.
> Fix SessionContext init with only SessionConfig

- .github/workflows/build.yml
- .github/workflows/conda.yml
> [!NOTE]
> The text of the PR has undergone significant changes since this morning on 2024-08-22. I noticed and tracked down some bugs in the build behavior that existed prior to this PR but went unnoticed. The result of that investigation is the two follow-on issues at the end.
Closes #724.
v3 will be disabled [2024-11-30](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
The change between `actions/upload-artifact@v3` and `v4` that impacted us was that each artifact is now immutable.
With v3, a wheel would be built for each target platform and then uploaded to the same `dist` artifact, which would aggregate the artifacts in an archive.
With v4, all but the 1st attempt to upload to `dist` fails with [this …
> build(deps): upgrade actions/{upload,download}-artifact@v3 to v4

- .github/workflows/build.yml
- python/datafusion/functions.py
- python/datafusion/tests/test_aggregation.py
- python/datafusion/tests/test_dataframe.py
- python/datafusion/tests/test_expr.py
- python/datafusion/tests/test_functions.py
- python/datafusion/tests/test_sql.py
Adds format check for python files to match pre-commit
We are getting some commits that are reformatting code. It is likely some users have pre-commit on and some do not. We do currently check ruff, but not ruff format.
Enable ruff format in CI.
Apply formatting to 6 files.
None. Just code cleanliness.
> Run ruff format in CI

- docs/source/user-guide/io/arrow.rst
- docs/source/user-guide/io/index.rst
- examples/import.py
- python/datafusion/context.py
- python/datafusion/dataframe.py
- python/datafusion/tests/test_context.py
- python/datafusion/tests/test_dataframe.py
- src/context.rs
- src/dataframe.rs
Closes #752 
User requested.
With this change you can import any arrow table that implements the PyCapsule Interface using the `SessionContext.from_arrow_table` function. Additionally, PyCapsule export of DataFrame is added. Now any python based project that uses python arrow with the pycapsule interface can directly consume a datafusion dataframe.
The DataFrame will be executed at the point of export.
You can see a minimal example in the issue ticket.
This PR adds `SessionContext.from_arrow` which served the same purpose as `from_arrow_table` except that it now takes any object that implements the required PyCapsule functions. `from_arrow_table` is now an alias to `from_arrow`.
> Add PyCapsule support for Arrow import and export

- .gitignore
- docs/source/user-guide/common-operations/aggregations.rst
- docs/source/user-guide/common-operations/windows.rst
- python/datafusion/dataframe.py
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/datafusion/tests/test_dataframe.py
- python/datafusion/tests/test_functions.py
- src/dataframe.rs
- src/expr.rs
- src/expr/window.rs
- src/functions.rs
This addresses part of #780 but we need a follow on PR to handle the aggregates.
In DataFusion 41 we have added the ability to create builders for the parameters for window and aggregate functions. These are more expressive when it comes to setting the window frame, ordering, partition, and null handling. This MR exposes this functionality on the python side.
Added functions
- lead
- lag
- row_number
- rank
- dense_rank
- percent_rank
- cume_dist
- ntile
Also updated the window function page of the online documentation to include links to these, examples of how to use them, and a description of how to set the additional parameters.
Updated the unit tests.
There are no breaking changes, but the old functions.window has been marked as deprecated. We can change this if needed because it is …
> Add Window Functions for use with function builder

- .github/workflows/build.yml
Closes #831
GH updated the runner images.
macos-14 is now ARM64.
macos-13 is last x86_64.
The build steps for `mac` have been updated.
This fix means we actually get a build wheel for `x86_64` on `macos`.
Example the `dist.zip` [this build](https://github.com/apache/datafusion-python/actions/runs/10567528280):
```console
unzip -- -l dist.zip
Archive:  dist.zip
Length      Date    Time    Name
---------  ---------- -----   ----
17180608  08-26-2024 21:49   datafusion-40.0.0-cp38-abi3-macosx_10_12_x86_64.whl
15600059  08-26-2024 21:49   datafusion-40.0.0-cp38-abi3-macosx_11_0_arm64.whl
19048084  08-26-2024 21:49   datafusion-40.0.0-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
18111348  08-26-2024 21:49   datafusion-40.0.0-cp38-abi3-manylinux_2_28_aarch64.whl
18464214  08-26-2024 …
```
> build(ci): use proper mac runners

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/dataframe.py
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/datafusion/tests/test_dataframe.py
- python/datafusion/tests/test_expr.py
- src/dataframe.rs
Closes #713
Closes #807
Closes #810
Also no issue assigned but fixes a bug in `functions.array()`
These are a handful of usability improvements.
- Adds `_repr_html_` to get a nice output in notebooks
- Allows for using `[]` to access array elements in an expression. If column `a` is a list of integers you could do `col(a)[0]` to get the first element in the list.
- Fixes an error in `array` so it operates correctly.
- Adds `DataFrame.transform()` which makes chaining dataframe operations easier.
No API changes, but the above all enhance usability.
> Set of small features

- python/datafusion/tests/test_context.py
- src/context.rs
Closes #796.
Change from the broad Exception to a specific KeyError exception. 
Yes
> feat: better exception and message for table not found

- python/datafusion/context.py
- python/datafusion/expr.py
- python/datafusion/functions.py
NA
Fixing some minor details in the documentation and some additional typos
No
> chore: fix docstrings, typos

- docs/source/contributor-guide/introduction.rst
Closes #779.
The introduction of the `python` wrappers necessitates some guideline for separating code.
A section is added to the contributor guide.
No.
> add guidelines on separating python and rust code

- docs/source/user-guide/common-operations/aggregations.rst
- python/datafusion/common.py
- python/datafusion/dataframe.py
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/datafusion/tests/test_aggregation.py
- python/datafusion/tests/test_functions.py
- python/datafusion/tests/test_wrapper_coverage.py
- src/functions.rs
Closes #780 
This PR follows the same pattern as the recently closed #808 but does the same for aggregate functions. This is a usability enhancement.
This PR updates the signatures for the aggregate functions to take optional parameters for the following:
- order_by
- distinct
- null_treatment
- filter
We add these parameters to the aggregate functions based on which ones are used internally. The other options are not in the function call. Users can always add these using the builder function approach if any of the internals get updated at a later time.
> Update Aggregate functions to take builder parameters

- python/datafusion/expr.py
- python/datafusion/tests/test_functions.py
- src/expr.rs
> feat: expose between

- Cargo.lock
- Cargo.toml
- python/datafusion/context.py
- python/datafusion/dataframe.py
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/datafusion/tests/test_expr.py
- python/datafusion/tests/test_sql.py
- python/datafusion/tests/test_wrapper_coverage.py
- src/common/data_type.rs
- src/common/schema.rs
- src/context.rs
- src/dataframe.rs
- src/dataset.rs
- src/dataset_exec.rs
- src/expr.rs
- src/expr/sort.rs
- src/expr/sort_expr.rs
- src/expr/window.rs
- src/functions.rs
- src/pyarrow_filter_expression.rs
- src/udf.rs
Closes #870.
This PR contains changes required to update to Datafusion v42, Arrow v53, and pyo3 v22
> Upgrade datafusion

- python/datafusion/tests/test_udaf.py
- python/datafusion/udf.py
Closes #874 
`datafusion-python` 41.1.0 introduced a regression on `SessionContext.register_udaf`. This two line change corrects it.
Correct regression.
Adds unit test for registering udaf and udf.
None
> Fix regression on register_udaf

- .github/workflows/build.yml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
Closes #578.
(Really, supersedes that PR).
Bumping this GH Action dependency is the last active `dependabot` PR.
`arduino/setup-protoc@v3` could not find our old version number of `3.20.2`.
I chose `protoc` [version 27.4](https://github.com/protocolbuffers/protobuf/releases/tag/v27.4) because it's the last release from the prior version.
`arduino/setup-protoc` action is updated from v1 to v3.
`protoc` version is updated from `3.20.2` to `27.4`.
There should not be.
> build(deps): upgrade setup-protoc action and protoc version number

- python/datafusion/tests/test_context.py
Closes #800.
This PR includes a test to demonstrate the issue, which was resolved with an upstream PR: https://github.com/apache/arrow-rs/issues/6318.
I have now rebased the PR against latest on main, which includes that upstream PR and thus the tests pass.
`df.count()` succeeds on arrow datasets.
> fix: Calling `count` on a pyarrow dataset results in an error

- python/datafusion/tests/test_sql.py
These tests are now passing, so I've removed the `xfail` from them.
`pyarrow.parquet` does not preserve `timestamp[s]` data type roundtrip between write and read.
https://github.com/apache/arrow/issues/41382
No.
> chore: remove XFAIL from passing tests

- python/datafusion/context.py
- python/datafusion/tests/test_sql.py
- src/context.rs
N/A
The method `read_csv` accepts a list of paths as input. It seems fitting that `register_csv` does the same. Moreover, it will solve the issue behind https://github.com/ibis-project/ibis/issues/9866.
Enable users to supply a list of csv file paths to the `register_csv` function.
Changes to the `register_csv` function in Rust and the corresponding signature types in Python 
Yes
> feat: make register_csv accept a list of paths

- docs/source/user-guide/common-operations/udf-and-udfa.rst
- examples/python-udwf.py
- python/datafusion/__init__.py
- python/datafusion/context.py
- python/datafusion/tests/test_udwf.py
- python/datafusion/udf.py
- src/context.rs
- src/lib.rs
- src/udwf.rs
Closes #845 
Currently users can only create user defined scalar functions and user defined window functions. This enables authoring user defined window functions. It is a core functionality that has been missing on the python library.
Designed similar to the UDAF, we have an abstract class for UDWF that users must inherit from.
Adds new udwf() function and WindowUDF class.
> Add user defined window function support

- examples/sql-parquet-s3.py
Closes #.
Example of reading parquet from S3 doesn't work because wrong number of arguments passed to `register_object_store()` function.
This PR fixes `register_object_store()` call.
No.
> fix example of reading parquet from s3

- benchmarks/tpch/create_tables.sql
The `WITH HEADER ROW` and `DELIMETER` clauses are no longer in use, and upstream datafusion errors out with a message saying so.
> WITH HEADER ROW clause is no longer in use. Please use the OPTIONS clause with 'format.has_header' set appropriately, e.g., OPTIONS (format.has_header true)
> DELIMITER clause is no longer in use. Please use the OPTIONS clause with 'format.delimiter' set appropriately, e.g., OPTIONS (format.delimiter ',')
> chore(bench): fix create_tables.sql for tpch benchmark

- Cargo.lock
- Cargo.toml
- python/datafusion/__init__.py
- python/datafusion/context.py
- python/datafusion/dataframe.py
- python/datafusion/expr.py
- python/datafusion/plan.py
- python/datafusion/substrait.py
- python/datafusion/tests/test_plans.py
- src/physical_plan.rs
- src/sql/logical.rs
Closes #869 
User requested, and also opens up functionality in datafusion-ray
Exposes `to_proto` and `from_proto` on logical and physical plans.
Pure addition.
TODO:
> Add physical and logical plan conversion to and from protobuf

- .github/workflows/conda.yml
Closes #893.
It is being sunsetted and will stop working entirely in Jan 2025.
Ref: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
Removes the `mambaforge` variant for our `conda` CI.
No.
> chore(ci): remove Mambaforge variant from CI

- Cargo.toml
- python/datafusion/__init__.py
- src/context.rs
- src/dataframe.rs
- src/lib.rs
- src/utils.rs
Closes #737.
To avoid repeatedly recreating the tokio runtime, https://github.com/apache/datafusion-python/pull/341 began storing the tokio runtime on the python heap at `datafusion.runtime`. 
This created the requirement that the `datafusion` python package must be available to any user of the rust crate `datafusion-python`.
However, some users (#737) want to leverage the rust-crate `datafusion-python` to create their own custom python package without depending on or using the python `datafusion` package.
This PR uses `std::sync::OnceLock` instead of the python heap to ensure that only one tokio runtime gets created once.
This both removes the implicit dependency and avoids `rust --> python --> rust` roundtrip every time the runtime is used.
`datafusion.runtime` has been removed, but …
> Use OnceLock to store TokioRuntime

- Cargo.toml
- python/datafusion/context.py
- python/datafusion/object_store.py
- python/tests/test_sql.py
- python/tests/test_store.py
- python/tests/test_wrapper_coverage.py
- src/context.rs
- src/store.rs
N/A
Reading csv from HTTP directly
The HTTP ObjectStore is exposed.
Yes
> feat: expose http object store

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
- wasn't exposed yet and very useful instead of a verbose select
- exposes datafusion-rust drop_columns as drop
- 
- exposes `drop` method
> feat: expose `drop` method

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
Was not yet exposed but very useful for inequality joins.
- Adds `join_on` method, which takes expressions
- new method
> feat: expose `join_on`

- python/datafusion/context.py
@timsaucer we could probably drop the rust code for from_pandas and from_polars and keep those in Python as aliases but just call from_arrow or even drop them. The only thing is we will have to add minimum dependencies since they recently added arrow_c_stream support. For polars that would be v1.3. For pandas I would have to check.
- better type hint than `Any`
- adds type hints for types that have arrow_c_stream
- 
None
> refactor: `from_arrow` use protocol typehints

- python/datafusion/expr.py
- python/datafusion/functions.py
- python/tests/test_expr.py
- src/functions.rs
Fill_na/null is a quite common method for doing this by other dataframe libraries (spark, polars, pandas)
- adds nvl function in functions api
- creates fill_nan/fill_null in expr namespace
> feat: add fill_null/nan expressions

- pyproject.toml
Closes #923.
The current project allows for a Python version >=3.6, but pyarrow versions >=11.0.0 require Python >=3.7, causing a dependency resolution conflict. This PR adjusts the Python version compatibility to prevent errors during dependency installation in environments using older Python versions (like Python 3.6).
Updated the requires-python field in pyproject.toml to reflect Python >=3.7 for better compatibility with pyarrow versions >=11.0.0.
This prevents potential dependency conflicts when installing pyarrow with Python 3.6, which is no longer supported by recent versions of pyarrow.
This change restricts the use of Python versions below 3.7 in the project. Users on Python 3.6 will need to upgrade their environment to use the latest version of the project.
> Change requires-python version in pyproject.toml

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
-  closes https://github.com/apache/datafusion-python/issues/838
Gives more flexibility to the user.
Adds a `with_columns` which is a wrapper around with_column in Rust, the schema_name of the expr is used as the name. However I think we could improve over this in a follow up, since we should keep the original  name unless somewhere down the expr path alias was called.
See this example of Polars VS Datafusion now:
original df
```python
+---+---+---+
| a | b | c |
+---+---+---+
| 1 | 4 | 8 |
| 2 | 5 | 5 |
| 3 | 6 | 8 |
+---+---+---+
```
Polars
```python
df.with_columns(pl.col('a)+5)
┌─────┬─────┬─────┐
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ i64 ┆ i64 ┆ i64 │
╞═════╪═════╪═════╡
│ 6   ┆ 4   ┆ 8   │
│ 7   ┆ 5   ┆ 5   │
│ 8 …
```
> feat: add `with_columns`

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
A top level cast is very practical and a common practice to do, since it's just a projection of columns, we call with_columns underneath. Therefore it builds on top of: https://github.com/apache/datafusion-python/pull/909,  so that one needs to be merged first.
- adds a `cast` method which takes in a mapping of col_names and dtypes. 
Important: I am going to work soon on creating a datafusion-python native schema struct and classes. Because going to pyarrow is simply to painful :) and then we can also drop the pyarrow dependency for that part
- adds new method.
> feat: add `cast` to DataFrame

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
Common methods similar to pyspark/polars/pandas api
-  Adds a head method, which  uses limit underneath.  Same as tail but calls the count of the dataframe to know where to start returning it from
> feat: add `head`, `tail` methods

- docs/source/user-guide/common-operations/select-and-filter.rst
- examples/import.py
- examples/tpch/convert_data_to_parquet.py
- examples/tpch/q02_minimum_cost_supplier.py
- examples/tpch/q03_shipping_priority.py
- examples/tpch/q04_order_priority_checking.py
- examples/tpch/q05_local_supplier_volume.py
- examples/tpch/q06_forecasting_revenue_change.py
- examples/tpch/q07_volume_shipping.py
- examples/tpch/q08_market_share.py
- examples/tpch/q09_product_type_profit_measure.py
- examples/tpch/q10_returned_item_reporting.py
- examples/tpch/q11_important_stock_identification.py
- examples/tpch/q12_ship_mode_order_priority.py
- examples/tpch/q13_customer_distribution.py
- examples/tpch/q14_promotion_effect.py
- examples/tpch/q15_top_supplier.py
- examples/tpch/q16_part_supplier_relationship.py
- examples/tpch/q17_small_quantity_order.py
- examples/tpch/q18_large_volume_customer.py
- examples/tpch/q19_discounted_revenue.py
- examples/tpch/q20_potential_part_promotion.py
- examples/tpch/q21_suppliers_kept_orders_waiting.py
- examples/tpch/q22_global_sales_opportunity.py
- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
Aliases in my opinion bloat the API, in this case it's also just nearly the same as select so we can just deprecate it and only keep select as that is clear enough. This will also improve code readability when you look at datafusion code.
- marks `select_columns` as deprecated
- marks `select_columns` as deprecated
> chore: deprecate `select_columns`

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/functions.py
- python/tests/test_functions.py
- src/functions.rs
This PR introduces a new function, array_empty, to check if an array is empty, returning a boolean.
Added the array_empty function. 
Updated the Python bindings in functions.py and provided unit tests for array_empty in test_functions.py.
Updated the documentation (expressions.rst) to include examples on how to use the new array_empty function.
The array_empty function is now available for users working with arrays. It is exposed both in Rust and Python, allowing users to check whether arrays are empty within their DataFusion queries.
There are no breaking changes to public APIs.
> Add array_empty scalar function

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/functions.py
- python/tests/test_functions.py
- src/functions.rs
This PR introduces a new function, cardinality, which returns the number of distinct elements in a array
Added the cardinality function. 
Updated the Python bindings in functions.py and provided unit tests for cardinality in test_functions.py.
Updated the documentation (expressions.rst) to include examples on how to use the new cardinality function.
The cardinality function is now available for users working with arrays. It is exposed both in Rust and Python, allowing users to obtain the number of distinct elements in their DataFusion queries.
There are no breaking changes to public APIs.
> add `cardinality` function to calculate total distinct elements in an array

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/functions.py
- python/tests/test_functions.py
This PR introduces a new function `empty` as alias of array_empty, to check if an array is empty, returning a boolean.
Added the empty function. 
Updated the Python bindings in functions.py and provided unit tests for empty in test_functions.py.
Updated the documentation (expressions.rst) to include examples on how to use the new empty function.
The array_empty function is now available for users working with arrays. It is exposed both in Rust and Python, allowing users to check whether arrays are empty within their DataFusion queries.
There are no breaking changes to public APIs.
> Add empty scalar function (alias of array_empty), fix a small typo

- docs/source/user-guide/common-operations/joins.rst
- examples/tpch/_tests.py
- examples/tpch/q02_minimum_cost_supplier.py
- examples/tpch/q03_shipping_priority.py
- examples/tpch/q04_order_priority_checking.py
- examples/tpch/q05_local_supplier_volume.py
- examples/tpch/q07_volume_shipping.py
- examples/tpch/q08_market_share.py
- examples/tpch/q09_product_type_profit_measure.py
- examples/tpch/q10_returned_item_reporting.py
- examples/tpch/q11_important_stock_identification.py
- examples/tpch/q12_ship_mode_order_priority.py
- examples/tpch/q13_customer_distribution.py
- examples/tpch/q14_promotion_effect.py
- examples/tpch/q15_top_supplier.py
- examples/tpch/q16_part_supplier_relationship.py
- examples/tpch/q17_small_quantity_order.py
- examples/tpch/q18_large_volume_customer.py
- examples/tpch/q19_discounted_revenue.py
- examples/tpch/q20_potential_part_promotion.py
- examples/tpch/q21_suppliers_kept_orders_waiting.py
- examples/tpch/q22_global_sales_opportunity.py
- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
Many times join keys are the same in both dataframes, so a simple on suffices. Also join_keys are deprecated  over left_on and right_on.
- marks join_keys as deprecated
- introduces on, left_on, right_on parameters
- adds function overloads
-  new params added, join_keys deprecated.
> refactor: dataframe `join` params

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/functions.py
- python/tests/test_functions.py
Completes 3 tasks in #463
This PR adds new functions `list_cat`, `list_concat`, `list_repeat`.
Added the `list_cat`, `list_concat`, `list_repeat` functions.
Updated the Python bindings in functions.py and provided unit tests in test_functions.py.
Updated the documentation (expressions.rst) to include examples on how to use the new functions.
The list_cat, list_concat, list_repeat functions are now available for users working with arrays allowing users to concatenate and repeat arrays within their DataFusion queries.
There are no breaking changes to public APIs.
> Add list_cat, list_concat, list_repeat

- python/datafusion/functions.py
- python/tests/test_functions.py
This PR introduces a new function, make_list, which is an alias for the existing make_array function and also tests.
Functionality: Added a new function make_list in functions.py, which is an alias for make_array.
Tests: Updated test_functions.py to include parameterized tests for both make_array and make_list, ensuring consistency in functionality.
Yes, the addition of the make_list function expands the API, providing users with a new way to achieve the same behavior as make_array.
> Add make_list and tests for make_list, make_array

- examples/python-udwf.py
N/A
The `python-udwf.py` is failing with:
> `func` must be callable.
Made the example match the tests 
No
> fix: udwf example

- docs/source/user-guide/common-operations/functions.rst
- python/datafusion/functions.py
- python/tests/test_functions.py
This PR introduces the implementation of the EXTRACT function, which allows extracting specific temporal units (e.g., YEAR, MONTH, DAY) from date or timestamp fields. It is an alias of `date_part`.
Functionality:
Adds the implementation of the EXTRACT subscalar function, it supports extracting temporal units like YEAR, MONTH, DAY, etc., from supported date, timestamp, and time data types.
Tests:
Adds tests for EXTRACT.
Yes, this PR adds the EXTRACT function to the API, enabling users to perform temporal extraction operations directly.
> Add datafusion.extract

- python/datafusion/dataframe.py
- python/datafusion/functions.py
- src/functions.rs
None
During testing of the DF 43.0.0 release we discovered that the `datafusion.functions.window` would fail to find default window functions if a session context is not provided.
Search for default window functions in addition to default aggregate functions.
None, internal only.
> Search default window functions if no session context was provided

- python/datafusion/context.py
- src/context.rs
- src/dataframe.rs
- src/utils.rs
- closes https://github.com/apache/datafusion-python/issues/950
> chore: set validation and type hint for ffi tableprovider

- examples/create-context.py
- python/datafusion/context.py
- src/context.rs
Closes #.
without url table support, we have to create table, if we want to query a file.
support enable_url_table config
No
> feat: support enable_url_table config

- Cargo.lock
- Cargo.toml
- python/datafusion/record_batch.py
- python/tests/test_dataframe.py
- src/record_batch.rs
Closes #974 .
Support async iteration of RecordBatchStream.
- Move into Rust raising `StopIteration` or `AsyncStopIteration` errors
- Update typing
- Add dependency on pyo3-async-runtimes to manage future conversion.
- Move `SendableRecordBatchStream` into an `Arc<Mutex<>>`. This is required I think so that we can clone the stream into `future_into_py`
Adds async iterator support.
> Support async iteration of RecordBatchStream

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- src/dataframe.rs
Closes #978.
Currently, the write_parquet method defaults to "uncompressed" Parquet files, which can lead to inefficient storage and slower performance during I/O operations. This change sets the default compression method to "ZSTD", a modern compression algorithm that provides an excellent balance of compression speed and ratio. Additionally, it introduces a default compression level of 3 for ZSTD, which is optimal for many use cases.
Updated the default compression parameter in the write_parquet method from "uncompressed" to "ZSTD".
Introduced a default compression level of 3 for ZSTD if no level is specified.
Added validation to ensure the compression level for ZSTD falls within the valid range (1 to 22) and raises a ValueError otherwise.
Updated the docstring to clarify the default …
> Default to ZSTD compression when writing Parquet 

- Cargo.lock
- Cargo.toml
- docs/source/contributor-guide/introduction.rst
- python/tests/test_indexing.py
- src/catalog.rs
- src/common/data_type.rs
- src/config.rs
- src/context.rs
- src/dataframe.rs
- src/dataset_exec.rs
- src/errors.rs
- src/expr.rs
- src/expr/conditional_expr.rs
- src/expr/literal.rs
- src/expr/window.rs
- src/functions.rs
- src/lib.rs
- src/physical_plan.rs
- src/pyarrow_filter_expression.rs
- src/pyarrow_util.rs
- src/record_batch.rs
- src/sql/exceptions.rs
- src/sql/logical.rs
- src/substrait.rs
- src/udaf.rs
- src/udwf.rs
- src/utils.rs
This addresses part of https://github.com/apache/datafusion/issues/14197
Closes #971
By removing the `pyarrow` dependency of DataFusion we can update `pyo3` in without requiring corresponding updates to the DataFusion core repository. This does add in a few additional pieces, such as adding a wrapper around `ScalarValue`, but it will simplify the core DataFusion repo to not have pyo3 in it.
- Removes `pyarrow` feature of DataFusion core repo
- Adds `PyScalarValue` which is a simple wrapper on `ScalarValue` so we can do things like implement traits on it that are currently implemented upstream in DataFusion.
- Renames `DataFusionError` to `PyDataFusionError` so there is not confusion with the enum defined upstream.
No user facing changes.
> feat: remove DataFusion pyarrow feat

- dev/release/verify-release-candidate.sh
Closes #.
When verifying the release using `./dev/release/verify_release_candidate.sh 44.0.0 1`  I got the following error
```
Requirement already satisfied: pip in ./.venv/lib/python3.11/site-packages (24.3.1)
Collecting pip
Using cached pip-25.0-py3-none-any.whl.metadata (3.7 kB)
Using cached pip-25.0-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
Attempting uninstall: pip
Found existing installation: pip 24.3.1
Uninstalling pip-24.3.1:
Successfully uninstalled pip-24.3.1
Successfully installed pip-25.0
+ python3 -m pip install -r requirements-310.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements-310.txt'
+ cleanup
+ '[' no = yes ']'
+ echo 'Failed to verify release candidate. See …
```
> Fix verify-release-candidate script by removing reference to requirements-310.txt

- python/datafusion/functions.py
- python/tests/test_functions.py
- src/functions.rs
No
to_timestamp_nanos has a wrapper, but not exported from rust.
export to_timestamp_nanos to python
no
> fix: add to_timestamp_nanos

- README.md
- docs/source/contributor-guide/ffi.rst
- docs/source/index.rst
Closes #1027 
User requested.
Adds a page to the online documentation.
None
> Add user documentation for the FFI approach

- python/datafusion/__init__.py
- python/datafusion/io.py
- python/tests/test_io.py
- python/tests/test_wrapper_coverage.py
- src/context.rs
- src/utils.rs
- closes https://github.com/apache/datafusion-python/issues/918
> feat: reads using global ctx

- python/datafusion/__init__.py
- python/datafusion/udf.py
- python/tests/test_udaf.py
- python/tests/test_udf.py
Closes #806
This PR implements decorators for `udf` and `udaf` to make UDF creation more easily.
Idea was suggested by: https://github.com/apache/datafusion-site/pull/17#discussion_r1714218915
- Implemented two decorator methods and exposed them to the users. The internal logic is simple because it serves as a wrapper to the actual `udf/udaf` methods.
- Added test cases to validate that the decorator methods are equivalent to the original APIs.
- Slight modification in `tests/test_udf.py` to make the `is_null` test cases more reliable. Previously, since all data are not null, the return value is always `[False, False, False]`, which is the same as the default empty vector. It caused confusion during my development because it didn't fail when I had a wrong implementation. I changed one …
> feat: Implementation of udf and udaf decorator

- examples/python-udwf.py
- pyproject.toml
- python/datafusion/io.py
- python/tests/test_udaf.py
- python/tests/test_udwf.py
None
During testing a user discovered a missing futures import that broke importing datafusion.
- Enable ruff lint for futures
- Fix offending files
None
> Add ruff check for missing futures import

- .github/workflows/take.yml
None
Copied from the datafusion repo to allow users to comment "take" and have an issue assigned to them.
Add github workflow
None
> Enable take comments to assign issues to users

- Cargo.toml
- docs/source/contributor-guide/introduction.rst
- examples/ffi-table-provider/Cargo.lock
- examples/ffi-table-provider/Cargo.toml
- examples/ffi-table-provider/pyproject.toml
- pyproject.toml
- uv.lock
> Update python min version to 3.9

- pyproject.toml
- python/tests/test_dataframe.py
- uv.lock
Closes #991.
Adding tests for Async Iteration of `RecordBatchStream`.
Adds tests, and adds pytest-asyncio to dev packages.
No.
> test: add pytest asyncio tests

- python/datafusion/udf.py
- python/tests/test_udwf.py
Closes #1057.
This PR improves the WindowUDF.udwf function by making it more flexible and user-friendly. It introduces function overloads and allows usage as both a function and a decorator, improving usability and code clarity. Additionally, it expands test coverage to ensure correctness and robustness.
Added function overloads to WindowUDF.udwf to support both function and decorator usage.
Refactored udwf to separate core logic into _create_window_udf and _create_window_udf_decorator for better maintainability.
Introduced helper methods _get_default_name and _normalize_input_types to simplify input handling.
Updated the test_udwf.py test suite to:
Add new test cases for function and decorator usage.
Introduce additional fixture-based DataFrame test setups.
Cover error cases, argument …
> Add decorator for udwf

- python/datafusion/functions.py
- python/tests/test_functions.py
- src/functions.rs
Closes (https://github.com/apache/datafusion-python/issues/803) partially
Expose additional regex functions to the python wrapper of datafusion
It exposes the regex-count function in datafusion to datafusion-python
Python users will now be able to use the regex-count method on their dataframes
> feat: expose regex_count function

- python/tests/test_dataframe.py
- src/dataframe.rs
- src/utils.rs
None.
The notebook rendering of DataFrames is very useful, but it can be enhanced. This PR adds quality of life improvements such as
- The table is now scrollable both vertically and horizontally
- Instead of collecting an arbitrary 10 rows, we collect up to 2 MB worth of data
- For Scalars that render to long strings (25 characters) we limit them down and have a `...` button to allow expanding the cell so you can view it in it's entirety
- When we have more data available than is displayed we indicate this to the user that the data are truncated
- When there are no data returned, we write this to the user
This PR adds a feature to collect record batches and uses their size estimate to collect up to 2MB worth of data. This is typically enough for most use cases to review the data, but it …
> Improve collection during repr and repr_html

- Cargo.lock
- Cargo.toml
- python/tests/test_dataframe.py
- src/expr.rs
- src/expr/aggregate.rs
- src/expr/aggregate_expr.rs
- src/expr/window.rs
- src/functions.rs
- src/utils.rs
None
In preparing for the next release, update the datafusion dependency.
Corresponding changes in the Expr representation due to upstream changes. Window and Aggregate functions have a slight change to their structs.
None. These are all internal changes.
> feat: Update DataFusion dependency to 46

- python/datafusion/__init__.py
- python/datafusion/unparser.py
- python/tests/test_unparser.py
- src/lib.rs
- src/unparser/dialect.rs
- src/unparser/mod.rs
datafusion support unparsing logical plan into sql. it's very useful for debugging logical plan.
add unparsing wrapper.
unparsing API.
> feat: support unparser

- docs/source/user-guide/basics.rst
Currently, the [basics page](https://datafusion.apache.org/python/user-guide/basics.html) in the Python docs mentions the Pokemon dataset while in fact NYC taxi data is used.
This MR simply mentions the correct dataset.
> Documentation updates: mention correct dataset on basics page

- python/datafusion/expr.py
- python/datafusion/functions.py
- python/tests/test_expr.py
- python/tests/test_functions.py
- src/expr.rs
- src/functions.rs
No
datafusion has supported alias_with_metadata, but python binding doesn't support it yet.
update alias method to accept optional metadata argument.
UT
> feat: alias with metadata

- python/datafusion/__init__.py
- python/datafusion/col.py
- python/tests/test_expr.py
Closes #1075 
To improve ergonomics of the API by providing a quicker way of accessing columns using the `__getattr__` method of classes. Using the `__call__` method, the original behavior is maintained, this is only additive.
Now this is possible
```python
from datafusion import col as c
my_a_column=c.a
my_banana_column=c.banana
```
A new col.py file with the class. I removed the col and column function from `__init__` and imported col and column from col.py. I added a test that duplicates another test but uses the new syntax.
Only optional ones as mentioned above.
No breaking changes.
> 1075/enhancement/Make col class with __getattr__

- python/datafusion/expr.py
Works towards closing #1064 
To improve ergonomics of the API by adding functions to the Expr class so that they can be chained
This includes function definitions in the Expr class for all the single argument functions that take Expr and return Expr
Yes, users can use functions chained from other Exprs for example `col("a").abs().tan()`
No breaking changes.
> 1064/enhancement/add functions to Expr class

- .asf.yaml
This is a change to the `.asf.yaml` file that requires an approving review to merge to `main`. I copied the configuration from our upstream `datafusion` repository.
> ci: require approving review

- src/errors.rs
- src/expr.rs
None. Fixes CI.
With the update to rustc 1.87 CI is now broken due to the error size of `DataFusionError`. This boxes that type to reduce the error type size.
Minor. Box the DataFusionError.
None.
> minor: reduce error size

- python/tests/test_expr.py
Follow on to https://github.com/apache/datafusion-python/issues/1116
We don't have code coverage for these expression functions
Unit tests
None
> add unit tests for expression functions

- python/datafusion/context.py
- python/datafusion/io.py
- python/tests/test_sql.py
- src/context.rs
Closes #1155
Following [datafusion PR4221](https://github.com/apache/datafusion/pull/4221), this PR exposes the functionality in the python bindings
Change of the `table_partition_cols` arguments in `PySessionContext.register_listing_table`,
`PySessionContext.register_parquet`, `PySessionContext.register_avro`, `PySessionContext.register_json`,
`PySessionContext.read_parquet`, `PySessionContext.read_avro`, `PySessionContext.read_json`
Yes, the signature of the functions above is changed
> Support types other than String and Int for partition columns

- Cargo.lock
- Cargo.toml
- dev/changelog/48.0.0.md
- examples/datafusion-ffi-example/Cargo.lock
None
Release 48.0.0
Update version.
Update changelog.
> 48.0.0 Release

- python/datafusion/expr.py
Closes #1176 
Resolves the `df.select( ^ SyntaxError: '(' was never closed` error in the example found in the [**datafusion.expr.CaseBuilder**](https://datafusion.apache.org/python/autoapi/datafusion/expr/index.html#datafusion.expr.CaseBuilder) example.
> docs: fix CaseBuilder documentation example

- docs/source/user-guide/data-sources.rst
Closes #1223 
Repoints the URL to the example project.
> docs: update link to user example for custom table provider

- docs/source/user-guide/common-operations/expressions.rst
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/tests/test_functions.py
This is a user request but no issue was opened.
With this you can do slicing of arrays via expression. For example, suppose you have this data frame:
```
+----------------------+
| a                    |
+----------------------+
| [1.0, 2.0, 3.0, 3.0] |
| [4.0, 5.0, 3.0]      |
| [6.0]                |
+----------------------+
```
You could do `df.with_column("a[1:3]", column("a")[1:3])` to get
```
+----------------------+------------+
| a                    | a[1:3]     |
+----------------------+------------+
| [1.0, 2.0, 3.0, 3.0] | [2.0, 3.0] |
| [4.0, 5.0, 3.0]      | [5.0, 3.0] |
| [6.0]                | []         |
+----------------------+------------+
```
Updates `__getitem__` to take slice.
Adds unit tests.
No
> feat: allow passing a slice to and expression with the [] indexing

- docs/source/user-guide/data-sources.rst
Closes #1159
Add documentations for the Iceberg <> Datafusion integration 
Rendered docs locally:
> docs: add apache iceberg as datafusion data source

- python/datafusion/dataframe.py
- python/tests/test_dataframe.py
- Strip quotes from column names in drop() method
- Maintains consistency with other DataFrame operations
- Both drop('col') and drop('col') now work
Rationale: CSV files with capitalized headers require quotes in `select()` operations but `drop()` failed when quotes were provided, creating inconsistent behavior across DataFrame methods.
User facing changes: users can now use either `drop('col')` or `drop('"col"')` consistently, matching the behavior of other DataFrame operations like `select()`.
Closes #1212
This is one of my first PRs, please let me know what I can improve!
> Fix drop() method to handle quoted column names consistently

- .github/workflows/build.yml
Closes #.
https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
replacing with `macos-15-intel` based on
https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories
> macos-13 is deprecated
