apache/datafusion-python

- src/context.rs
- src/lib.rs
Disable some lints until we can upgrade to pyo3 0.17
> Fix Clippy

- README.md
> [Doc] - Fix readme git repo url

- src/context.rs
> [SessionContext] - Add session_id funcation for session context

- src/context.rs
> [SessionContext] - Add register_udaf_fun funcation for session context

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
> [DataFrame] -  Add with_column_renamed funcation for dataframe

- datafusion/tests/test_context.py
- src/context.rs
> [SessionContext] - Add table_exist funcation for session context

- datafusion/tests/test_dataframe.py
- src/dataframe.rs
> [DataFrame] - Add cache function to DataFrame

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_catalog.py
- src/dataframe.rs
- src/dataset_exec.rs
- src/expression.rs
- src/functions.rs
- src/pyarrow_filter_expression.rs
> Upgrade to DataFusion 14.0.0

- .github/workflows/build.yml
Part of https://github.com/apache/arrow-datafusion-python/issues/7
We need to build wheels on rc tags as well as final release tags.
Change workflow to build on all tags
> Build wheels on all tags, not just "rc" tags

- pyproject.toml
Part of https://github.com/apache/arrow-datafusion-python/issues/7
I could not upload the wheels to testpypi due to the following error:
```
400 Invalid value for project_urls. Error: Use valid URL. 
```
Add `https://` prefix to urls.
> Fix project urls

- dev/release/README.md
Closes #.
this change is trivial and editorial
use `bash` not `py` for scripting
> update release readme tag

- src/functions.rs
> [Functions] - Add python function binding to `functions`

- .github/dependabot.yml
- .github/workflows/build.yml
- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- dev/release/README.md
- dev/release/create-tarball.sh
- dev/release/update_change_log-datafusion-python.sh
- docs/source/conf.py
Part of https://github.com/apache/arrow-datafusion-python/issues/144
See issue
Replace `master` with `main` where needed
No
> Rename default branch from master to main

- Cargo.lock
- Cargo.toml
N/A
Pick up bug fixes and new features
> Use DataFusion rev 5238e8c97f998b4d2cb9fab85fb182f325a1a7fb

- Cargo.lock
- Cargo.toml
- src/substrait.rs
> Use latest DataFusion rev in preparation for DF 18 release

- datafusion/__init__.py
- datafusion/common.py
- datafusion/tests/test_imports.py
- src/common.rs
- src/common/df_schema.rs
- src/lib.rs
Closes #181 
Bindings for DFSchema in datafusion_common::DFSchemaRef
> Add bindings for DFSchema

- CHANGELOG.md
> Update changelog for 0.8 release

- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/sort.rs
> Add Python wrapper for LogicalPlan::Sort

- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/aggregate.rs
Part of https://github.com/apache/arrow-datafusion-python/issues/191
> Add Python wrapper for LogicalPlan::Aggregate

- datafusion/tests/test_expr.py
- src/sql/logical.rs
> Add tests for recently added functionality

- Cargo.lock
- datafusion/__init__.py
- datafusion/tests/test_imports.py
- src/expr.rs
- src/expr/empty_relation.rs
- src/expr/indexed_field.rs
> Add bindings for GetIndexedField

- CHANGELOG.md
- dev/release/README.md
Closes https://github.com/apache/arrow-datafusion-python/issues/237
> Fix release instructions

- Cargo.lock
- Cargo.toml
> Upgrade to DataFusion 19

- Cargo.lock
- Cargo.toml
- src/lib.rs
> Re-export Datafusion dependencies

- Cargo.lock
- Cargo.toml
> Use DataFusion 20

- dev/release/README.md
- dev/release/rat_exclude_files.txt
> fix release process

- Cargo.toml
- dev/release/README.md
Closes https://github.com/apache/arrow-datafusion-python/issues/294
Only include necessary files in crate.
> add package.include and remove wildcard dependency

- CHANGELOG.md
- Cargo.lock
Closes #.
- cargo update
- Changelog
> Prepare 21.0.0 release

- .github/workflows/build.yml
Closes #.
Fix this error:
```
Invalid workflow file: .github/workflows/build.yml#L109
The workflow is not valid. .github/workflows/build.yml (Line: 109, Col: 13): A mapping was not expected
```
> Fix invalid build yaml

- .github/workflows/build.yml
- Cargo.toml
Closes https://github.com/apache/arrow-datafusion-python/issues/211
- Install protoc for non-containerized builds (mac/win)
- Speficy protoc feature for containerized builds (linux/source)
> Fix Mac/Win release builds in CI

- .github/workflows/docs.yaml
> install protoc in docs workflow

- Cargo.toml
- pyproject.toml
- requirements.in
Closes https://github.com/apache/arrow-datafusion-python/issues/317
> Source wheel fix

- .asf.yaml
N/A
Fix to correct user guide (Python not Rust)
> Fix link to user guide

- benchmarks/db-benchmark/README.md
- benchmarks/db-benchmark/db-benchmark.dockerfile
- benchmarks/db-benchmark/groupby-datafusion.py
- benchmarks/db-benchmark/join-datafusion.py
- benchmarks/db-benchmark/run-bench.sh
N/A
Move db-benchmark from arrow-datafusion repo to arrow-datafusion-python repo. This makes more sense because these are Python benchmarks.
There is a corresponding PR to remove this benchmark from the `arrow-datafusion` repo:
https://github.com/apache/arrow-datafusion/pull/6204
Move files from arrow-datafusion repo
Note that additional work is required to get these working again, such as updating some of the paths in the Dockerfile.
No
> Add db-benchmark

- .github/workflows/test.yaml
- benchmarks/db-benchmark/README.md
- benchmarks/db-benchmark/db-benchmark.dockerfile
- benchmarks/db-benchmark/groupby-datafusion.py
- benchmarks/db-benchmark/join-datafusion.py
- benchmarks/db-benchmark/run-bench.sh
- dev/python_lint.sh
N/A
Prepare scripts for submission to duckdb repo
Compare performance with Polars when running in Docker
> Improve db-benchmark

- src/common/data_type.rs
- src/expr.rs
> Make expr member of PyExpr public

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
N/A
Update bindings for latest DataFusion release
- Bump version
- Update changelog
> Prepare 24.0.0 Release

- src/common/data_type.rs
- src/expr.rs
- src/expr/projection.rs
- src/sql/logical.rs
> Expand Expr to include RexType basic support

- dev/release/README.md
- dev/release/generate-changelog.md
N/A
Adds the Python script that I use for generating changelog content when creating releases.
Yes, this script has been used for several releases.
No
> Add Python script for generating changelog

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- dev/release/generate-changelog.py
- src/expr.rs
- src/functions.rs
- src/pyarrow_filter_expression.rs
N/A
Update for latest DF release.
- Bump version
- Changelog ([rendered](https://github.com/andygrove/arrow-datafusion-python/blob/prep-25/CHANGELOG.md))
No
> Update for DataFusion 25.0.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- datafusion/tests/test_dataframe.py
- datafusion/tests/test_substrait.py
- dev/release/generate-changelog.py
- src/common/df_field.rs
- src/expr.rs
- src/expr/scalar_function.rs
- src/substrait.rs
Closes #.
- Upgrade to DF 26.0.0
- Changelog
> Prepare for 26.0.0 release

- Cargo.lock
- Cargo.toml
- datafusion/tests/test_functions.py
- src/common/data_type.rs
- src/dataset_exec.rs
- src/expr.rs
- src/expr/projection.rs
- src/functions.rs
N/A
Prepare for next release
Use DataFusion 28.0.0-rc1
> Upgrade to 28.0.0-rc1

- Cargo.lock
- Cargo.toml
- src/common/data_type.rs
- src/expr.rs
- src/expr/indexed_field.rs
- src/udaf.rs
> Upgrade to DF 28.0.0-rc1

- src/functions.rs
> Minor: fix wrongly copied function description

- dev/release/README.md
- dev/release/rat_exclude_files.txt
N/A
This PR fixes a couple of things that I have run into with recent releases
- RAT check was failing due to `.config/Cargo.toml` not having a license header, so I have added this to the ignore list
- The instructions for creating a source release were incorrect
- Documentation was missing some tasks, such as reporting the release to Apache Reporter, and deleting old releases
- Updated docs
- Add one file to rat exclude list
No
> Improve release process documentation

- Cargo.lock
- Cargo.toml
- src/context.rs
- src/expr/literal.rs
N/A
Update to latest DF 
Update to latest DF 
No
> Use latest DataFusion

- datafusion/tests/test_aggregation.py
- src/functions.rs
part of https://github.com/apache/arrow-datafusion-python/issues/466
> add bit_and,bit_or,bit_xor,bool_add,bool_or

- src/functions.rs
N/A
I ran clippy locally with Rust 1.73 and this change was suggested.
> Small clippy fix

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/expr.rs
> Prepare 33.0.0 Release

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- datafusion/tests/test_sql.py
- src/common/data_type.rs
- src/context.rs
- src/expr/window.rs
- src/functions.rs
N/A
Scheduled release
- Use DataFusion 35.0.0
- Update changelog
> Prepare 35.0.0-rc1

- datafusion/tests/test_functions.py
- src/functions.rs
> More missing array funcs

- Cargo.lock
- Cargo.toml
N/A
We cannot upload 38.0.0 RC2 to test.pypi.org so bumping to 38.0.1
> change version to 38.0.1

- CHANGELOG.md
> Update changelog for 39.0.0

- python/datafusion/expr.py
Fixes CI for newly added expressions
In #793 two expressions were added to the internal module that were not added to the wrapper.
Exposes these variants in the wrapper.
None. These are newly added.
> Add missing expressions to wrapper export

- benchmarks/db-benchmark/db-benchmark.dockerfile
- docs/mdbook/src/index.md
- docs/source/_static/theme_overrides.css
- docs/source/conf.py
- docs/source/user-guide/common-operations/expressions.rst
- examples/export.py
- examples/python-udf-comparisons.py
- examples/tpch/q02_minimum_cost_supplier.py
- examples/tpch/q04_order_priority_checking.py
- examples/tpch/q06_forecasting_revenue_change.py
- examples/tpch/q07_volume_shipping.py
- examples/tpch/q11_important_stock_identification.py
- examples/tpch/q15_top_supplier.py
- examples/tpch/q20_potential_part_promotion.py
- examples/tpch/q21_suppliers_kept_orders_waiting.py
- examples/tpch/q22_global_sales_opportunity.py
- python/datafusion/context.py
- python/datafusion/expr.py
- python/datafusion/functions.py
- python/datafusion/input/location.py
- python/datafusion/udf.py
- src/common/data_type.rs
- src/expr/table_scan.rs
None
Spelling correction
Among others: 
- run [codespell](https://github.com/codespell-project/codespell) on the source code
- change the name of the parameter in db-benchmark.dockerfile based on spelling suggestions and the documentation:
https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/install.packages
No
> chore: fix typos

- pyproject.toml
Closes #.
Fix two issues in pyproject.toml to fix linting (e.g. in vscode so the toml matches the expected schema of a pyproject.toml file).
- `classifier` should be `classifiers`
- We set the version to be `dynamic` because it's set by Cargo
No
> Fix small issues in pyproject.toml

- Cargo.lock
- Cargo.toml
No issue, this just updates a couple of dependencies to their newer versions. All changes are minor.
Prepare for release
> minor: Update dependencies prior to release

- Cargo.lock
- Cargo.toml
- dev/changelog/44.0.0.md
- pyproject.toml
- uv.lock
This is to prepare to release datafusion-python 44.0.0.
> Prepare release 44.0.0

- Cargo.lock
- Cargo.toml
- dev/changelog/46.0.0.md
> Update changelog and version number

- python/datafusion/expr.py
No
expr depends on functions.
functions depends on expr.
there's a recursive import.
import functions when it's needed.
No
> fix: recursive import

- Cargo.lock
- Cargo.toml
- dev/changelog/49.0.0.md
- examples/datafusion-ffi-example/Cargo.lock
- examples/datafusion-ffi-example/Cargo.toml
Closes https://github.com/apache/datafusion-python/issues/1209
Next release.
Update cargo lock, changelog, and version number.
No
> 49.0.0 release
